[websubhub.consolidator.config.server]
port = 10001

[websubhub.consolidator.config.state.snapshot]
topic = "websub-events-snapshot"
consumerId = "websub-events-snapshot-consumer"

[websubhub.consolidator.config.state.events]
topic = "websub-events"
consumerId = "consolidator-websub-events-consumer"

[websubhub.consolidator.config.store.kafka]
bootstrapServers = "localhost:9092"

[websubhub.consolidator.config.store.kafka.producer]
acks = "all"
retryCount = 3

[websubhub.consolidator.config.store.kafka.consumer]
maxPollRecords = 50
pollingInterval = 10.0
gracefulClosePeriod = 5.0

# [websubhub.consolidator.config.store.solace]
# url = "tcp://localhost:55554"
# messageVpn = "default"
# auth.username = "admin"
# auth.password = "admin"

# [websubhub.consolidator.config.store.solace.consumer]
# receiveTimeout = 10.0

# [websubhub.consolidator.config.store.solace.admin]
# url = "http://localhost:8080/SEMP/v2/config"
# timeout = 30.0
# auth.username = "admin"
# auth.password = "admin"

[ballerina.log]
level = "INFO"
