blank_issues_enabled: false
contact_links:
- name: 'ðŸ“š Documentation Issue'
  about: Request a new article, missing topic, or report an issue if a topic is incorrect in the current documentation.
  url: https://github.com/wso2/docs-websubhub/issues/new/choose
